import type { ProductCategory } from "../types";

export const productCategories: ProductCategory[] = [
  {
    id: "md-tables",
    name: "MD Tables",
    slug: "md-tables",
    description: "Premium executive tables designed for directors and managing offices.",
    sortOrder: 1,
    active: true,
  },
  {
    id: "manager-tables",
    name: "Manager Tables",
    slug: "manager-tables",
    description: "Modern manager desks for professional workspaces.",
    sortOrder: 2,
    active: true,
  },
  {
    id: "workstations",
    name: "Workstations",
    slug: "workstations",
    description: "Modular workstation systems for collaborative offices.",
    sortOrder: 3,
    active: true,
  },
  {
    id: "conference-tables",
    name: "Conference Tables",
    slug: "conference-tables",
    description: "Conference and meeting room tables.",
    sortOrder: 4,
    active: true,
  },
  {
    id: "reception-tables",
    name: "Reception Tables",
    slug: "reception-tables",
    description: "Reception desks for office entrances.",
    sortOrder: 5,
    active: true,
  },
  {
    id: "storage",
    name: "Storage & Pedestals",
    slug: "storage",
    description: "Office storage cabinets and pedestals.",
    sortOrder: 6,
    active: true,
  },
  {
    id: "discussion-tables",
    name: "Discussion Tables",
    slug: "discussion-tables",
    description: "Discussion and collaboration tables.",
    sortOrder: 7,
    active: true,
  },
  {
    id: "executive-chairs",
    name: "Executive Chairs",
    slug: "executive-chairs",
    description: "Premium executive seating.",
    sortOrder: 8,
    active: true,
  },
  {
    id: "visitor-chairs",
    name: "Visitor Chairs",
    slug: "visitor-chairs",
    description: "Comfortable visitor seating.",
    sortOrder: 9,
    active: true,
  },
  {
    id: "cafeteria-furniture",
    name: "Cafeteria Furniture",
    slug: "cafeteria-furniture",
    description: "Furniture for cafeterias and dining spaces.",
    sortOrder: 10,
    active: true,
  },
  {
    id: "high-counter-tables",
    name: "High Counter Tables",
    slug: "high-counter-tables",
    description: "High counter and bar-height tables.",
    sortOrder: 11,
    active: true,
  },
];
